dist: xenial
matrix:
    include:
        - language: python
          python: 3.7
          install:
              - cd $TRAVIS_BUILD_DIR
              - pip install -r backend/requirements.txt
          script:
              - cd $TRAVIS_BUILD_DIR/backend
              - coverage run --source=swpp manage.py test
          after_success:
              - coveralls
        - language: node_js
          node_js: "6.9"
          install:
              - cd $TRAVIS_BUILD_DIR/frontend
              - npm install
          script:
              - cd $TRAVIS_BUILD_DIR/frontend
              - npm test -- --coverage
          after_success:
              - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
