dist: xenial
matrix:
    include:
        - language: python
          python: 3.7
          install: pip install django djangorestframework django-annoying coverage
          script:
              - cd backend
              - coverage run --source=swpp manage.py test
          after_success:
              - coveralls
