# Generated by Django 2.2 on 2019-04-16 06:43

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0003_profile_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('profile', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swpp.Profile')),
                ('bio', models.TextField()),
            ],
        ),
    ]
