# Generated by Django 2.1.7 on 2019-04-30 15:45

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0004_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField(default='')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='')),
                ('payment', models.TextField(default='')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swpp.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BigIntegerField(default=0)),
                ('tue', models.BigIntegerField(default=0)),
                ('wed', models.BigIntegerField(default=0)),
                ('thu', models.BigIntegerField(default=0)),
                ('fri', models.BigIntegerField(default=0)),
                ('sat', models.BigIntegerField(default=0)),
                ('sun', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='exp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='times',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swpp.Times'),
        ),
        migrations.AddField(
            model_name='request',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='swpp.Profile'),
        ),
        migrations.AddField(
            model_name='request',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='swpp.Tutor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='swpp.Tag'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='lectures',
            field=models.ManyToManyField(to='swpp.Lecture'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='times',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpp.Times'),
        ),
    ]
