# Generated by Django 2.1.7 on 2019-05-01 06:16

import annoying.fields
from django.db import migrations
import django.db.models.deletion
import swpp.model.tutor


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0005_auto_20190501_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='times',
            field=annoying.fields.AutoOneToOneField(default=swpp.model.tutor.default_times, on_delete=django.db.models.deletion.CASCADE, to='swpp.Times'),
        ),
    ]
