# Generated by Django 2.2.1 on 2019-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0006_auto_20190501_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
