# Generated by Django 2.2.1 on 2019-05-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0007_auto_20190505_2010'),
        ('swpp', '0007_auto_20190504_2155'),
    ]

    operations = [
    ]
