# Generated by Django 2.1.7 on 2019-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0008_merge_20190506_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.TextField(default='010-0000-0000'),
        ),
    ]
