# Generated by Django 2.2.1 on 2019-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0009_auto_20190519_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
