# Generated by Django 2.1.7 on 2019-06-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0011_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpp.Lecture'),
        ),
    ]
