# Generated by Django 2.1.7 on 2019-06-03 08:39

import annoying.fields
from django.db import migrations
import django.db.models.deletion
import swpp.model.tutor


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0012_auto_20190603_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutoringTimes',
            field=annoying.fields.AutoOneToOneField(default=swpp.model.tutor.default_times, on_delete=django.db.models.deletion.CASCADE, related_name='tutoringTimes', to='swpp.Times'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='times',
            field=annoying.fields.AutoOneToOneField(default=swpp.model.tutor.default_times, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='swpp.Times'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
