# Generated by Django 2.1.7 on 2019-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0013_auto_20190603_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '대기중'), (1, '진행중'), (2, '완료')], default=0),
        ),
    ]
