# Generated by Django 2.1.7 on 2019-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpp', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
